openapi: '3.0.2'
info:
  title: Version
  version: '1.0'
servers:
  - url: https://bigdata.f3rva.org
  - url: http://devbigdata.brianbischoff.com
    description: Server description
paths:
  /version:
    get:
      summary: Returns the current version
      responses:
        '200':
          description: JSON payload with the version information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Version'
        '405':
          description: Requested method not allowed

components:
  schemas:
    Version:
      type: object
      properties:
        version:
          type: string
          example: v1.0.1

