name: F3RVA API CD

on: 
  workflow_dispatch:
    inputs:
      releasePrefix:
        description: 'Prefix for all release names'
        required: true
        default: 'release'
      versionNumber:
        description: 'Version to deploy'
        required: true
        default: 'vX.X.X'

jobs:

  # deploy
  # - get the deployment file from the release
  # - secure copy the file to the destination (stored in secrets)
  # - delete the old
  # - expand the file on the remote host (probably a deployment script)
  # - done

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        id: setup-environment
        run: |
          mkdir dist
      
      - name: Retrieve the deployment file from the release package
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "${{ github.event.inputs.versionNumber }}"
          file: "f3rva-api-${{ github.event.inputs.versionNumber }}.tar.gz"
          target: "dist/f3rva-api-${{ github.event.inputs.versionNumber }}.tar.gz"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List the tar contents
        id: tar-contents
        run: |
          tar tvfz dist/f3rva-api-${{ github.event.inputs.versionNumber }}.tar.gz
