name: F3RVA API CD

on: 
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version to deploy'
        required: true
        default: 'vX.X.X'

jobs:

  # TODO
  # - secure copy the file to the destination (stored in secrets)
  # - delete the old
  # - expand the file on the remote host (probably a deployment script)
  # - done

  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Download
      uses: robinraju/release-downloader@v1.3
      with:
        repository: "f3rva/f3rva-api"
        latest: false
        tag: "${{ github.event.inputs.versionNumber }}"
        fileName: "f3rva-api-${{ github.event.inputs.versionNumber }}.tar.gz"
        out-file-path: "dist"
        tarBall: false
        zipBall: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        port: ${{ secrets.DEPLOY_PORT }}
        key: ${{ secrets.DEPLOY_KEY }}
        passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
        source: "./dist/f3rva-api-${{ github.event.inputs.versionNumber }}.tar.gz"
        target: "./public_html/dev.bigdata.f3rva"
    
    - name: Extract
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        port: ${{ secrets.DEPLOY_PORT }}
        key: ${{ secrets.DEPLOY_KEY }}
        passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
        script: |
          cd ./public_html/dev.bigdata.f3rva
          tar xvfz f3rva-api-${{ github.event.inputs.versionNumber }}.tar.gz
