name: F3RVA API CD

on: 
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version to deploy'
        required: true
        default: 'vX.X.X'
      environmentKey:
        description: 'Environment'
        required: true
        default: 'dev'

jobs:
  params:
    if: ${{ github.event.inputs.environmentKey == 'dev' }}
    uses: ./.github/workflows/properties-dev.yml

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environmentKey }}
    steps:
    - name: Download
      uses: robinraju/release-downloader@v1.3
      with:
        repository: "f3rva/f3rva-api"
        latest: false
        tag: "${{ github.event.inputs.versionNumber }}"
        fileName: "f3rva-api-${{ github.event.inputs.versionNumber }}.tar.gz"
        tarBall: false
        zipBall: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        port: ${{ secrets.DEPLOY_PORT }}
        key: ${{ secrets.DEPLOY_KEY }}
        passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
        source: "./f3rva-api-${{ github.event.inputs.versionNumber }}.tar.gz"
        target: "./deploy"
    
    - name: Extract
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        port: ${{ secrets.DEPLOY_PORT }}
        key: ${{ secrets.DEPLOY_KEY }}
        passphrase: ${{ secrets.DEPLOY_PASSPHRASE }}
        script: | 
          #rm -rf ${{ steps.deploy-path.outputs.value }}/*
          #cd ${{ steps.deploy-path.outputs.value }}
          #tar xvfz ../../deploy/f3rva-api-${{ github.event.inputs.versionNumber }}.tar.gz
          echo ${{ needs.params.outputs.deployPath }}

          # environment specific replacements
          sed -i -e 's/@@ENVIRONMENT_KEY@@/${{ github.event.inputs.environmentKey }}/g' public/.htaccess
          sed -i -e 's/@@DB_HOST@@/${{ secrets.DB_HOST }}/g' config/config-${{ github.event.inputs.environmentKey }}.php
          sed -i -e 's/@@DB_NAME@@/${{ secrets.DB_NAME }}/g' config/config-${{ github.event.inputs.environmentKey }}.php
          sed -i -e 's/@@DB_USER@@/${{ secrets.DB_USERNAME }}/g' config/config-${{ github.event.inputs.environmentKey }}.php
          sed -i -e 's/@@DB_PASS@@/${{ secrets.DB_PASSWORD }}/g' config/config-${{ github.event.inputs.environmentKey }}.php
