name: F3RVA API CD

on: 
  push:
    branches: [ $default-branch ]

jobs:

  # create distribution and deploy
  distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repo
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict
        
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-      - name: Install composer dependencies
      
      - name: Install composer dependencies
        run: composer install --prefer-dist

      - name: Run unit tests
        run: |
          composer test
        env:
          XDEBUG_MODE: coverage
      
      - name: Create distribution
        id: create-distribution
        run: |
          tar -cvfz dist/f3rva-api-LATEST.tar.gz \
          LICENSE \
          bootstrap.php \
          config \
          public \
          src \
          vendor \
        
      - uses: actions/upload-artifact@v2
        with:
          name: distribution
          path: ./dist/f3rva-api*.tar.gz
          retention-days: 7

