name: F3RVA API CD

on: 
  workflow_dispatch:
    inputs:
      versionNumber:
        description: 'Version to deploy'
        required: true
        default: 'vX.X.X'

jobs:

  # deploy
  # - get the deployment file from the release
  # - secure copy the file to the destination (stored in secrets)
  # - delete the old
  # - expand the file on the remote host (probably a deployment script)
  # - done

  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: robinraju/release-downloader@v1.3
      with:
        tag: "${{ github.event.inputs.versionNumber }}"
        fileName: "f3rva-api-${{ github.event.inputs.versionNumber }}.tar.gz"
        out-file-path: "dist"
        tarBall: true
        zipBall: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: List the tar contents
      id: tar-contents
      run: |
        tar tvfz dist/f3rva-api-${{ github.event.inputs.versionNumber }}.tar.gz
