name: F3RVA API CI

on: 
  - pull_request
  - push

jobs:

  # unit test configuration
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repo
        uses: actions/checkout@v2

  validate-composer:
    uses: ./.github/workflows/setup-composer.yml

  unit-test:
    runs-on: ubuntu-latest
    steps:      
      - name: Run unit tests
        run: |
          composer test
        env:
          XDEBUG_MODE: coverage
