name: F3RVA API CI

on: 
  push:
  pull_request:
    branches: [main]

jobs:

  # unit test configuration
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate
      
      - name: Install composer dependencies
        run: composer install --prefer-dist

      # unit test command
      - name: Run unit tests
        run: |
          composer test
        env:
          XDEBUG_MODE: coverage

