name: F3RVA API CI

on: 
  - pull_request
  - push

jobs:

  # unit test configuration
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repo
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict
        
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-      - name: Install composer dependencies
      
      - name: Install composer dependencies
        run: composer install --prefer-dist

      - name: Run unit tests
        run: |
          composer test
        env:
          XDEBUG_MODE: coverage
      
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: ./test-output/coverage
          retention-days: 7

