name: F3RVA API CI

on: 
  - pull_request
  - push

jobs:

  # unit test configuration
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from repo
        uses: actions/checkout@v2

      - name: Debug
        run: |
          pwd
          ls -laR
      - name: Validate composer.json and composer.lock
        uses: ./.github/workflows/setup-composer.yml
        
      - name: Run unit tests
        run: |
          composer test
        env:
          XDEBUG_MODE: coverage
