name: Setup Composer

on: 
  workflow_call:

jobs:

  # validate and install composer
  setup-composer:
    name: Validate and install composer dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Validate composer.json and composer.lock
        run: composer validate --strict
        
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-      - name: Install composer dependencies
      
      - name: Install composer dependencies
        run: composer install --prefer-dist
